---
title: 'R Notebook: Climate Data Analysis'
output:
  html_document: default
  html_notebook: default
---

Read in Data via url
```{r}
climate = read.table("http://www.stat.duke.edu/courses/Fall10/sta290/datasets/climate.dat",  header=T)
names(climate)
summary(climate)
```

Recode levels of T.M and Proxies

```{r}
climate$T.M  = factor(climate$T.M, labels= c("T", "M"))
climate$proxy = factor(climate$proxy, labels = c("Mg/Ca", "Alkenone", "Faunal", "Sr/Ca", "Del180", "IceCore", "Pollen", "Noble Gas"))
```

Plot dataframe

```{r}
plot(climate)
plot(deltaT ~ latitude, data=climate, col=1, pch = as.numeric(T.M)+23, bg = as.numeric(proxy), ylim=c(min(deltaT) - 2*max(sdev), max(deltaT) + 2*max(sdev)),
     ylab="Delta T")
title("Change in Temperature by Proxy")
abline(h=0, lty=2 )

attach(climate)
segments(latitude, deltaT-2*sdev, latitude, deltaT+2*sdev, lty=3)
points(latitude, deltaT, col=1, pch = as.numeric(T.M)+23, bg = as.numeric(proxy))

detach(climate)
```

Conditioning plots (coplot)

```{r}
coplot(deltaT ~ latitude | proxy, data=climate)
coplot(deltaT ~ latitude | T.M, data=climate)
```

Fit Linear Model as a weighted regression 

```{r}
climate.lm = lm(deltaT ~ proxy *(poly(latitude,2)), weights=(1/sdev^2), data=climate)
plot(climate.lm)
anova(climate.lm)

climate1.lm = lm(deltaT ~ poly(latitude,2) + proxy, weights=1/sdev^2,data=climate)
climate2.lm = lm(deltaT ~ proxy, weights=1/sdev^2,data=climate) 
climate3.lm = lm(deltaT ~ T.M, weights=(1/sdev^2), data=climate)



```

Compare sequential models using ANOVA
```{r}
anova(climate3.lm,climate2.lm,climate1.lm, climate.lm)
```

Added Variable plots:  

```{r}
library(car)

avPlots(climate1.lm, terms=~.)


attach(climate)
climate.lat.lm = lm(deltaT ~ latitude, data=climate, weights=1/sdev^2)
pred.deltaT = fitted(climate.lat.lm)

plot(deltaT ~ latitude, data=climate, col=1, pch = as.numeric(T.M)+23, bg = as.numeric(proxy), ylim=c(min(deltaT) - 2*max(sdev), max(deltaT) + 2*max(sdev)),
     ylab="Delta T")
lines(latitude[order(latitude)], pred.deltaT[order(latitude)], lwd=2)
title("Change in Temperature by Proxy")
abline(h=0, lty=2 )

segments(latitude, deltaT-2*sdev, latitude, deltaT+2*sdev, lty=3)
points(latitude, deltaT, col=1, pch = as.numeric(T.M)+23, bg = as.numeric(proxy))
#legend(-20,2, levels(proxy), pch=c(rep(24,5),rep(25,3)), col = as.numeric(proxy))

```

