---
title: "Homework Assignment 3"
abstract_short: ''
date: '2019-09-15'
draft: no
math: yes
selected: no
abstract: ''
url_pdf:
url_slides: ''
url_video: ''
---

** See Due Date in Sakai**

Please see the link in Sakai to the GitHub classroom invitation for the assignment

* You will be asked to identify your email on the roster  - please do so if you have not already. While the instruction say you can skip this step, please do not. This will link your github username to the roster. We will need that for creating team assignments later.

* Click on the "accept" button.

* after the repo is created it will show a link to your repo in the @sta721-F19 organization; click on the link and get started with the instructions in the README file adn see the pdf for the problem set and Rnw file.



Please push your final Rnw file and pdf file to the organization repo from your local repo by the due date to receive full credit on the assignment (3 points).

You should also upload your code and pdf onto Sakai.


Please start before class on Wednesday in case there are questions or clarifications needed (or post on Piazza).  For the data analysis part, please use R/RStudio with knitr/Sweave to create a  Rnw/pdf document to upload.   Use LaTeX (encouraged) or write by hand (must be legible) and scan to submit via Sakai for other problems.


Review Chapter 2 and Appendix C in [Plane Answers to Complex Questions](http://getitatduke.library.duke.edu/?sid=sersol&SS_jc=TC0000508493&title=Plane%20Answers%20to%20Complex%20Questions%3A%20The%20Theory%20of%20Linear%20Models) on Vector Spaces 

Review Material from the [StatSci Computing Bootcamp](https://github.com/shawnsanto/computing-bootcamp-2019) for `R` or other links under [Resources](/#resources)
